/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Degree service. Represents a row in the &quot;Sample_Degree&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.DegreeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.DegreeImpl}.
 * </p>
 *
 * @author jasonxiang
 * @see Degree
 * @see com.liferay.sample.model.impl.DegreeImpl
 * @see com.liferay.sample.model.impl.DegreeModelImpl
 * @generated
 */
public interface DegreeModel extends BaseModel<Degree> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a degree model instance should use the {@link Degree} interface instead.
	 */

	/**
	 * Returns the primary key of this degree.
	 *
	 * @return the primary key of this degree
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this degree.
	 *
	 * @param primaryKey the primary key of this degree
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the degree ID of this degree.
	 *
	 * @return the degree ID of this degree
	 */
	public long getDegreeId();

	/**
	 * Sets the degree ID of this degree.
	 *
	 * @param degreeId the degree ID of this degree
	 */
	public void setDegreeId(long degreeId);

	/**
	 * Returns the degree name of this degree.
	 *
	 * @return the degree name of this degree
	 */
	@AutoEscape
	public String getDegreeName();

	/**
	 * Sets the degree name of this degree.
	 *
	 * @param degreeName the degree name of this degree
	 */
	public void setDegreeName(String degreeName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.sample.model.Degree degree);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.sample.model.Degree> toCacheModel();

	@Override
	public com.liferay.sample.model.Degree toEscapedModel();

	@Override
	public com.liferay.sample.model.Degree toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}