/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Education service. Represents a row in the &quot;Sample_Education&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.EducationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.EducationImpl}.
 * </p>
 *
 * @author jasonxiang
 * @see Education
 * @see com.liferay.sample.model.impl.EducationImpl
 * @see com.liferay.sample.model.impl.EducationModelImpl
 * @generated
 */
public interface EducationModel extends BaseModel<Education> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a education model instance should use the {@link Education} interface instead.
	 */

	/**
	 * Returns the primary key of this education.
	 *
	 * @return the primary key of this education
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this education.
	 *
	 * @param primaryKey the primary key of this education
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the education ID of this education.
	 *
	 * @return the education ID of this education
	 */
	public long getEducationId();

	/**
	 * Sets the education ID of this education.
	 *
	 * @param educationId the education ID of this education
	 */
	public void setEducationId(long educationId);

	/**
	 * Returns the user ID of this education.
	 *
	 * @return the user ID of this education
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this education.
	 *
	 * @param userId the user ID of this education
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this education.
	 *
	 * @return the user uuid of this education
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this education.
	 *
	 * @param userUuid the user uuid of this education
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the school name of this education.
	 *
	 * @return the school name of this education
	 */
	@AutoEscape
	public String getSchoolName();

	/**
	 * Sets the school name of this education.
	 *
	 * @param schoolName the school name of this education
	 */
	public void setSchoolName(String schoolName);

	/**
	 * Returns the degree ID of this education.
	 *
	 * @return the degree ID of this education
	 */
	public long getDegreeId();

	/**
	 * Sets the degree ID of this education.
	 *
	 * @param degreeId the degree ID of this education
	 */
	public void setDegreeId(long degreeId);

	/**
	 * Returns the graduate year of this education.
	 *
	 * @return the graduate year of this education
	 */
	@AutoEscape
	public String getGraduateYear();

	/**
	 * Sets the graduate year of this education.
	 *
	 * @param graduateYear the graduate year of this education
	 */
	public void setGraduateYear(String graduateYear);

	/**
	 * Returns the recommender of this education.
	 *
	 * @return the recommender of this education
	 */
	@AutoEscape
	public String getRecommender();

	/**
	 * Sets the recommender of this education.
	 *
	 * @param recommender the recommender of this education
	 */
	public void setRecommender(String recommender);

	/**
	 * Returns the introduction of this education.
	 *
	 * @return the introduction of this education
	 */
	@AutoEscape
	public String getIntroduction();

	/**
	 * Sets the introduction of this education.
	 *
	 * @param introduction the introduction of this education
	 */
	public void setIntroduction(String introduction);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.sample.model.Education education);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.sample.model.Education> toCacheModel();

	@Override
	public com.liferay.sample.model.Education toEscapedModel();

	@Override
	public com.liferay.sample.model.Education toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}