/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Honour service. Represents a row in the &quot;Sample_Honour&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.HonourModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.HonourImpl}.
 * </p>
 *
 * @author jasonxiang
 * @see Honour
 * @see com.liferay.sample.model.impl.HonourImpl
 * @see com.liferay.sample.model.impl.HonourModelImpl
 * @generated
 */
public interface HonourModel extends BaseModel<Honour> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a honour model instance should use the {@link Honour} interface instead.
	 */

	/**
	 * Returns the primary key of this honour.
	 *
	 * @return the primary key of this honour
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this honour.
	 *
	 * @param primaryKey the primary key of this honour
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the honour ID of this honour.
	 *
	 * @return the honour ID of this honour
	 */
	public long getHonourId();

	/**
	 * Sets the honour ID of this honour.
	 *
	 * @param honourId the honour ID of this honour
	 */
	public void setHonourId(long honourId);

	/**
	 * Returns the honorary name of this honour.
	 *
	 * @return the honorary name of this honour
	 */
	@AutoEscape
	public String getHonoraryName();

	/**
	 * Sets the honorary name of this honour.
	 *
	 * @param honoraryName the honorary name of this honour
	 */
	public void setHonoraryName(String honoraryName);

	/**
	 * Returns the user ID of this honour.
	 *
	 * @return the user ID of this honour
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this honour.
	 *
	 * @param userId the user ID of this honour
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this honour.
	 *
	 * @return the user uuid of this honour
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this honour.
	 *
	 * @param userUuid the user uuid of this honour
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.sample.model.Honour honour);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.sample.model.Honour> toCacheModel();

	@Override
	public com.liferay.sample.model.Honour toEscapedModel();

	@Override
	public com.liferay.sample.model.Honour toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}