/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Major service. Represents a row in the &quot;Sample_Major&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.model.impl.MajorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.model.impl.MajorImpl}.
 * </p>
 *
 * @author jasonxiang
 * @see Major
 * @see com.liferay.sample.model.impl.MajorImpl
 * @see com.liferay.sample.model.impl.MajorModelImpl
 * @generated
 */
public interface MajorModel extends BaseModel<Major> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a major model instance should use the {@link Major} interface instead.
	 */

	/**
	 * Returns the primary key of this major.
	 *
	 * @return the primary key of this major
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this major.
	 *
	 * @param primaryKey the primary key of this major
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the major ID of this major.
	 *
	 * @return the major ID of this major
	 */
	public long getMajorId();

	/**
	 * Sets the major ID of this major.
	 *
	 * @param majorId the major ID of this major
	 */
	public void setMajorId(long majorId);

	/**
	 * Returns the major name of this major.
	 *
	 * @return the major name of this major
	 */
	@AutoEscape
	public String getMajorName();

	/**
	 * Sets the major name of this major.
	 *
	 * @param majorName the major name of this major
	 */
	public void setMajorName(String majorName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.sample.model.Major major);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.sample.model.Major> toCacheModel();

	@Override
	public com.liferay.sample.model.Major toEscapedModel();

	@Override
	public com.liferay.sample.model.Major toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}