/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.liferay.sample.model.Honour;
import com.liferay.sample.model.HonourModel;
import com.liferay.sample.model.HonourSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Honour service. Represents a row in the &quot;Sample_Honour&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.sample.model.HonourModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HonourImpl}.
 * </p>
 *
 * @author jasonxiang
 * @see HonourImpl
 * @see com.liferay.sample.model.Honour
 * @see com.liferay.sample.model.HonourModel
 * @generated
 */
@JSON(strict = true)
public class HonourModelImpl extends BaseModelImpl<Honour>
	implements HonourModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a honour model instance should use the {@link com.liferay.sample.model.Honour} interface instead.
	 */
	public static final String TABLE_NAME = "Sample_Honour";
	public static final Object[][] TABLE_COLUMNS = {
			{ "honourId", Types.BIGINT },
			{ "honoraryName", Types.VARCHAR },
			{ "userId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table Sample_Honour (honourId LONG not null primary key,honoraryName VARCHAR(75) null,userId LONG)";
	public static final String TABLE_SQL_DROP = "drop table Sample_Honour";
	public static final String ORDER_BY_JPQL = " ORDER BY honour.honourId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Sample_Honour.honourId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.sample.model.Honour"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.sample.model.Honour"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.sample.model.Honour"),
			true);
	public static long USERID_COLUMN_BITMASK = 1L;
	public static long HONOURID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Honour toModel(HonourSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Honour model = new HonourImpl();

		model.setHonourId(soapModel.getHonourId());
		model.setHonoraryName(soapModel.getHonoraryName());
		model.setUserId(soapModel.getUserId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Honour> toModels(HonourSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Honour> models = new ArrayList<Honour>(soapModels.length);

		for (HonourSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.sample.model.Honour"));

	public HonourModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _honourId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setHonourId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _honourId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Honour.class;
	}

	@Override
	public String getModelClassName() {
		return Honour.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("honourId", getHonourId());
		attributes.put("honoraryName", getHonoraryName());
		attributes.put("userId", getUserId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long honourId = (Long)attributes.get("honourId");

		if (honourId != null) {
			setHonourId(honourId);
		}

		String honoraryName = (String)attributes.get("honoraryName");

		if (honoraryName != null) {
			setHonoraryName(honoraryName);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}
	}

	@JSON
	@Override
	public long getHonourId() {
		return _honourId;
	}

	@Override
	public void setHonourId(long honourId) {
		_honourId = honourId;
	}

	@JSON
	@Override
	public String getHonoraryName() {
		if (_honoraryName == null) {
			return StringPool.BLANK;
		}
		else {
			return _honoraryName;
		}
	}

	@Override
	public void setHonoraryName(String honoraryName) {
		_honoraryName = honoraryName;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Honour.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Honour toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Honour)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HonourImpl honourImpl = new HonourImpl();

		honourImpl.setHonourId(getHonourId());
		honourImpl.setHonoraryName(getHonoraryName());
		honourImpl.setUserId(getUserId());

		honourImpl.resetOriginalValues();

		return honourImpl;
	}

	@Override
	public int compareTo(Honour honour) {
		long primaryKey = honour.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Honour)) {
			return false;
		}

		Honour honour = (Honour)obj;

		long primaryKey = honour.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		HonourModelImpl honourModelImpl = this;

		honourModelImpl._originalUserId = honourModelImpl._userId;

		honourModelImpl._setOriginalUserId = false;

		honourModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Honour> toCacheModel() {
		HonourCacheModel honourCacheModel = new HonourCacheModel();

		honourCacheModel.honourId = getHonourId();

		honourCacheModel.honoraryName = getHonoraryName();

		String honoraryName = honourCacheModel.honoraryName;

		if ((honoraryName != null) && (honoraryName.length() == 0)) {
			honourCacheModel.honoraryName = null;
		}

		honourCacheModel.userId = getUserId();

		return honourCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{honourId=");
		sb.append(getHonourId());
		sb.append(", honoraryName=");
		sb.append(getHonoraryName());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.liferay.sample.model.Honour");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>honourId</column-name><column-value><![CDATA[");
		sb.append(getHonourId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>honoraryName</column-name><column-value><![CDATA[");
		sb.append(getHonoraryName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Honour.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Honour.class };
	private long _honourId;
	private String _honoraryName;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _columnBitmask;
	private Honour _escapedModel;
}